FROM ubuntu:18.04


ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing \
    && apt-get install -y wget \
    bzip2 \
    ca-certificates \
    libglib2.0-0 \
    libnss3 \
    libasound2 \
    libxext6 \
    libsm6 \
    libxrender1 \
    git \
    mercurial \
    subversion

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN apt-get install -y curl grep sed dpkg && \
    TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && \
    curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && \
    dpkg -i tini.deb && \
    rm tini.deb && \
    apt-get clean
    
RUN apt-get install --fix-missing -y cmake \
    autoconf \
    build-essential \
    idle-python2.7 \
    libglew-dev \
    libgle3 \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libosmesa6-dev \
    libqtcore4 \
    libqt4-dbus \
    libqt4-network \
    libqt4-script \
    libqt4-test \
    libqt4-xml \
    libqtgui4 \
    libtool \
    patchelf \
    pkg-config \
    python-dev \
    python-opengl \
    python-pil \
    python-pyrex \
    python-pyside.qtopengl \
    python-qt4 \
    python-qt4-gl \
    python3-scipy \
    qt4-designer \
    qt4-dev-tools \
    unzip \
    xvfb \
    && python -m pip install --upgrade pip \
    && git clone https://github.com/openai/gym.git \
    && cd gym \
    && pip install -e . \
    && cd .. \
    && wget https://www.roboti.us/download/mjpro150_linux.zip \
    && mkdir -p $HOME/.mujoco/mjpro150 \
    && unzip mjpro150_linux.zip -d $HOME/.mujoco/mjpro150/ \
    && echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mjpro150/bin' ~/.bashrc \
    && git clone https://github.com/openai/mujoco-py.git \
    && cd mujoco-py \
    && python setup.py install \
    && cd .. \
    && conda install swig -y \
    && cd gym \
    && pip install -e '.[all]' \
    && pip uninstall box2d-py -y \
    && pip install keras \
    && pip install tensorflow \
    && pip install python-igraph

RUN git clone https://github.com/pybox2d/pybox2d \
    && cd pybox2d/ \
    && python setup.py clean \
    && python setup.py build \
    && python setup.py install


ENTRYPOINT ["/bin/bash"]